### ISSUE TITLE
QNAP arm docker problems

### ISSUE THREAD

**Issue by MartinY** [visibilityspots/dockerfile-cloudflared#40]
Until the last updates, the docker worked without problems in my QNAP
Now, log problems:
`r12     0x1033f94,
r13     0x1033f95,
r14     0x0,
r15     0x0,
r16     0x0,
r17     0x6,
r18     0x7f7e86b447,
r19     0xd0,
r20     0x4000131708,
r21     0x400048e160,
r22     0x16,
r23     0x0,
r24     0xffffffffffffffa2,
r25     0xd8af20,
r26     0x1664938,
r27     0x16fc35d,
r28     0x4000000180,
r29     0x4000130e68,
lr      0xb8dcc0,
sp      0x4000130e70,
pc      0xb8e4c0,
fault   0x0,
SIGILL: illegal instruction,
PC=0xb8e4c0 m=0 sigcode=1,
instruction bytes: 0x0 0x6 0x38 0xd5 0xe0 0x7 0x0 0xf9 0xc0 0x3 0x5f 0xd6 0x0 0x0 0x0 0x0,
,
goroutine 1 [running, locked to thread]:,
golang.org/x/sys/cpu.getisar0(0x400007f110),
	/tmp/release/vendor/golang.org/x/sys/cpu/cpu_arm64.s:14 fp=0x4000138e70 sp=0x4000138e70 pc=0xb8e4c0,
golang.org/x/sys/cpu.readARM64Registers(),
	/tmp/release/vendor/golang.org/x/sys/cpu/cpu_arm64.go:65 +0x30 fp=0x4000138eb0 sp=0x4000138e70 pc=0xb8dcc0,
golang.org/x/sys/cpu.doinit(),
	/tmp/release/vendor/golang.org/x/sys/cpu/cpu_linux_arm64.go:38 +0x2c fp=0x4000138ed0 sp=0x4000138eb0 pc=0xb8dfbc,
golang.org/x/sys/cpu.archInit(),
	/tmp/release/vendor/golang.org/x/sys/cpu/cpu_arm64.go:45 +0x20 fp=0x4000138ee0 sp=0x4000138ed0 pc=0xb8dc70,
golang.org/x/sys/cpu.init.0(),
	/tmp/release/vendor/golang.org/x/sys/cpu/cpu.go:199 +0x20 fp=0x4000138ef0 sp=0x4000138ee0 pc=0xb8d220,
runtime.doInit(0x1664900),
	/usr/local/go/src/runtime/proc.go:6308 +0xdc fp=0x4000139050 sp=0x4000138ef0 pc=0x44775c,
runtime.doInit(0x16711e0),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x40001391b0 sp=0x4000139050 pc=0x4476e0,
runtime.doInit(0x16646c0),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x4000139310 sp=0x40001391b0 pc=0x4476e0,
runtime.doInit(0x1663800),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x4000139470 sp=0x4000139310 pc=0x4476e0,
runtime.doInit(0x166c940),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x40001395d0 sp=0x4000139470 pc=0x4476e0,
runtime.doInit(0x1666a20),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x4000139730 sp=0x40001395d0 pc=0x4476e0,
runtime.doInit(0x166fd80),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x4000139890 sp=0x4000139730 pc=0x4476e0,
runtime.doInit(0x166e9a0),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x40001399f0 sp=0x4000139890 pc=0x4476e0,
runtime.doInit(0x166a960),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x4000139b50 sp=0x40001399f0 pc=0x4476e0,
runtime.doInit(0x1667f80),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x4000139cb0 sp=0x4000139b50 pc=0x4476e0,
runtime.doInit(0x1672540),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x4000139e10 sp=0x4000139cb0 pc=0x4476e0,
runtime.doInit(0x166e3a0),
	/usr/local/go/src/runtime/proc.go:6285 +0x60 fp=0x4000139f70 sp=0x4000139e10 pc=0x4476e0,
runtime.main(),
	/usr/local/go/src/runtime/proc.go:208 +0x214 fp=0x4000139fd0 sp=0x4000139f70 pc=0x4395d4,
runtime.goexit(),
	/usr/local/go/src/runtime/asm_arm64.s:1130 +0x4 fp=0x4000139fd0 sp=0x4000139fd0 pc=0x46e3f4,
,
r0      0x1,
r1      0x400012a3a0,
r2      0x4000138eb0,
r3      0x0,
r4      0x0,
r5      0x1049d20,
r6      0x1000,
r7      0x6,
r8      0xf9,
r9      0x400007f13f,
r10     0x1000,
r11     0x1,
r12     0x1033f94,
r13     0x1033f95,
r14     0x0,
r15     0x0,
r16     0x0,
r17     0x6,
r18     0x7f87b5d447,
r19     0xd0,
r20     0x4000139708,
r21     0x400048e160,
r22     0x16,
r23     0x0,
r24     0xffffffffffffffa2,
r25     0xd8af20,
r26     0x1664938,
r27     0x16fc35d,
r28     0x4000000180,
r29     0x4000138e68,
lr      0xb8dcc0,
sp      0x4000138e70,
pc      0xb8e4c0,
fault   0x0`

It gives me the impression that it is not detecting well the version of arm that it has to download and that is why it fails. any ideas?

**Comment by visibilityspots** [comment]
I don't have a QNAP system to test on, works fine on other ARM based devices though..
